repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # You can change this to the latest prettier mirror version
    hooks:
      - id: prettier
        files: \.(json|md)$
