/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChainProfile {
  name: string;
  pretty_name: string;
  chain_id?: string;
  category: "DeFi" | "Social" | "NFT" | "Gaming" | "Portfolio" | "AI" | "Consumer" | "Others";
  /**
   * @maxItems 3
   */
  tags?: [] | [string] | [string, string] | [string, string, string];
  /**
   * A longer description for the landing page
   */
  description: string;
  /**
   * A short description for the onboarding page (less than or equal to 50 characters)
   */
  summary?: string;
  logo: string;
  /**
   * Modify saturation and luminance for the ecosystem or the vip
   */
  color?: string;
  status: "live" | "upcoming" | "hidden";
  vip?: {
    actions?: {
      title?: string;
      description?: string;
      [k: string]: unknown;
    }[];
    forum_url?: string;
    [k: string]: unknown;
  };
  social?: {
    website?: string;
    twitter?: string;
    [k: string]: unknown;
  };
  l2?: boolean;
  [k: string]: unknown;
}
