name: Check Broken Links

on:
  schedule:
    - cron: "0 10 1,15 * *" # Run on 1st and 15th days of every month at 10:00 UTC
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: read
  issues: write

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: --accept 501 --exclude-loopback --verbose --no-progress --exclude '^.*(%7D)$' './**/*.json' './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
