name: Deploy Anvil Privnode

on:
  push:
    paths:
      - 'testnets/**/chain.json'
      - 'mainnets/**/chain.json'
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-privnode:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [ asia-southeast, europe-west ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed chain.json files
        id: changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^testnets/.*/chain\.json$|^mainnets/.*/chain\.json$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        if: steps.changed.outputs.files != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.changed.outputs.files != ''
        run: npm install firebase-admin axios

      - name: Write service account JSON
        if: steps.changed.outputs.files != ''
        run: |
          echo '${{ secrets.FIREBASE_ANVIL_SERVICE_ACCOUNT }}' >> sa.json

      - name: Deploy Privnode in ${{ matrix.region }}
        if: steps.changed.outputs.files != ''
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_ANVIL_API_KEY }}
          BASE_URL: "https://api.anvil.${{ matrix.region }}.initia.xyz"
          REGION: ${{ matrix.region }}
          CHANGED_FILES: ${{ steps.changed.outputs.files }}
        run: node ./.github/workflows/utility/deploy_privnode.js
