name: NPM create initia-registry pull request

on:
  push:
    branches: ['main']
    paths:
      - '*/*/assetlist.json'
      - '*/*/chain.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  create_initia_registry_pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install semver
        run: npm install -g semver
      - name: Update version
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version") 
          NEW_VERSION=$(npx semver $CURRENT_VERSION -i patch)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          COMMIT=$(git rev-parse --short HEAD)
          echo "commit=COMMIT" >> $GITHUB_OUTPUT
          npm version $NEW_VERSION --no-git-tag-version
        working-directory: ./_packages/initia-registry
      - name: Install dependencies and update initia-registry-types
        run: |
          npm ci
          npm uninstall @initia/initia-registry-types
          npm install @initia/initia-registry-types
        working-directory: ./_packages/initia-registry
      - name: Generate files
        run: npm run build:pkg
        working-directory: ./_packages/initia-registry
      - name: Format fix
        run: npm run format:fix
        working-directory: ./_packages/initia-registry
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          title: '[BOT] Update initia-registry to ${{ steps.version.outputs.new_version }}'
          commit-message: '[BOT] Update initia-registry to ${{ steps.version.outputs.new_version }}'
          body: 'Update initia-registry to ${{ steps.version.outputs.new_version }}'
          branch: 'bump/initia-registry-${{steps.version.outputs.commit}}'
