name: NPM publish initia-registry-types

on:
  push:
    branches: ["main"]
    paths:
      - _packages/types/package.json

permissions:
  id-token: write
  contents: read

jobs:
  publish_types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
        working-directory: ./_packages/types
      - run: npm run build
        working-directory: ./_packages/types
      - run: npm publish
        working-directory: ./_packages/types
