name: Validate Data
on: [pull_request]

jobs:
  jobname:
    name: Validate Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Get changed files (chain.json / assetlist.json)
        id: changed
        run: |
          files=$(git diff --name-only origin/${{ github.base_ref }} | while read file; do
            case "$(basename "$file")" in
              chain.json|assetlist.json) echo "$file";;
            esac
          done)
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install js-sha3 ethers

      - name: Validate changes
        if: steps.changed.outputs.files != ''
        run: |
          for file in ${{ steps.changed.outputs.files }}; do
            echo "Validating $file"
            base_name=$(basename "$file")
            if [[ "$base_name" == "chain.json" ]]; then
              node ./.github/workflows/utility/validaote_chain.js
            elif [[ "$base_name" == "assetlist.json" ]]; then
              node ./.github/workflows/utility/validaote_assetlist.js
            fi
          done
